<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hourglass.Core\Hourglass.Core.csproj" />
    <ProjectReference Include="..\Hourglass.Platform\Hourglass.Platform.csproj" />
  </ItemGroup>
</Project>
